In [1]:
import csv

with open('tmax_2012.csv', 'r') as tempfile:
    csv_reader = csv.reader(tempfile)

    #with open('new_tempfile.csv', 'w') as new_file:


FileNotFoundError: [Errno 2] No such file or directory: 'tmax_2012.csv'

In [1]:
import csv
with open('tmax_2012.csv', 'r') as tempfile:

SyntaxError: unexpected EOF while parsing (<ipython-input-1-34adca2e7996>, line 2)

FileNotFoundError: [Errno 2] No such file or directory: 'tmax_2012.csv'

In [5]:
pwd

'/Users/fiker/Desktop/sci research'

In [6]:
import csv
with open('tmax_2012.csv', 'r') as tempfile:

SyntaxError: unexpected EOF while parsing (<ipython-input-6-34adca2e7996>, line 2)

In [7]:
import csv

with open('tmax_2012.csv', 'r') as tempfile:
    csv_reader = csv.reader(tempfile)
for line in tempfile:
    print(line)

FileNotFoundError: [Errno 2] No such file or directory: 'tmax_2012.csv'

In [9]:
import csv

with open('tmax_2012.csv', 'r') as tempfile:
    csv_reader = csv.reader(tempfile)
for line in tempfile:
    print(line)

FileNotFoundError: [Errno 2] No such file or directory: 'tmax_2012.csv'

In [10]:
import numpy as np

In [11]:
filename = "tmax_2012.csv"

In [13]:
filename = "tmax_2012.csv"

In [14]:
filename = "tmax_2012c.csv"

In [15]:
data = np.loadtxt(filename, delimiter=",")

In [16]:
for line in data:
    print(line)

[ 1.      1.     18.5075]
[ 1.      2.     15.5127]
[1.      3.      7.23089]
[1.      4.      7.84532]
[ 1.      5.     14.1394]
[ 1.      6.     17.3237]
[ 1.      7.     18.6015]
[ 1.      8.     17.7445]
[ 1.      9.     17.7377]
[ 1.     10.     16.5817]
[ 1.     11.     15.9421]
[ 1.     12.     15.4064]
[ 1.    13.    10.228]
[ 1.      14.       8.62032]
[ 1.     15.     11.9815]
[ 1.    16.    13.264]
[ 1.     17.     15.2547]
[ 1.     18.     15.1075]
[ 1.     19.     12.4934]
[ 1.     20.     13.4808]
[ 1.     21.     16.5115]
[ 1.    22.    15.631]
[ 1.    23.    14.835]
[ 1.     24.     16.7934]
[ 1.     25.     19.2788]
[ 1.     26.     19.6938]
[ 1.     27.     17.5399]
[ 1.     28.     16.0147]
[ 1.     29.     15.0412]
[ 1.     30.     15.2794]
[ 1.     31.     17.5751]
[ 2.      1.     18.3736]
[ 2.     2.    18.813]
[ 2.      3.     18.4841]
[ 2.     4.    18.688]
[ 2.      5.     19.6304]
[ 2.      6.     17.3668]
[ 2.      7.     15.1529]
[ 2.      8.     15.8617]
[

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("tmax_2012c.csv")

In [ ]:
df.columns=['Month','Day','Temp']

In [ ]:
df.iloc[:,-1]=((df.iloc[:,-1])*9/5)+35 
#change all values in last column from C to F using formula

In [ ]:
print(df.iloc[:,-1])

In [2]:
import numpy as np
v = np.linspace(0,10,5)

In [3]:
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
first= 2.2

In [5]:
v[0]=first

In [6]:
v

array([ 2.2,  2.5,  5. ,  7.5, 10. ])